server:
  port: 7001
spring: 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
  thymeleaf:
    cache: false